openapi: "3.0.3"
info:
  title: "Multimedia Tours API"
  description: "Multimedia Tours API"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8090"
paths:
  /multimedia-objects:
    post:
      summary: Create a new multimediaObject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MultimediaObjectRequest'
      responses:
        '201':
          description: MultimediaObject created successfully
        '400':
          description: Bad request
      tags:
        - Multimedia Objects
    get:
      summary: Retrieve all MultimediaObjects
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: { }
        '404':
          description: MultimediaObjects not found
      tags:
        - Multimedia Objects
  /multimedia-objects/{id}:
    get:
      summary: Retrieve a MultimediaObject by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: { }
        '404':
          description: MultimediaObject not found
      tags:
        - Multimedia Objects
    delete:
      summary: Delete MultimediaObject by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: MultimediaObject deleted successfully
        '400':
          description: Bad request
        '404':
          description: MultimediaObject not found
      tags:
        - Multimedia Objects
    patch:
      summary: Update MultimediaObject by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MultimediaObjectRequest'
      responses:
        '200':
          description: MultimediaObject updated successfully
        '400':
          description: Bad request
        '404':
          description: MultimediaObject not found
      tags:
        - Multimedia Objects

  /tours:
    post:
      summary: Create a new tour
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TourRequest'
      responses:
        '201':
          description: Tour created successfully
        '400':
          description: Bad request
      tags:
        - Tours
    get:
      summary: Retrieve all Tours
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: { }
        '404':
          description: Tours not found
      tags:
        - Tours
  /tours/{id}:
    get:
      summary: Retrieve a Tour by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: { }
        '404':
          description: Tour not found
      tags:
        - Tours
    delete:
      summary: Delete Tour by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tour deleted successfully
        '400':
          description: Bad request
        '404':
          description: Tour not found
      tags:
        - Tours
    patch:
      summary: Update Tour by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TourRequest'
      responses:
        '200':
          description: Tour updated successfully
        '400':
          description: Bad request
        '404':
          description: Tour not found
      tags:
        - Tours
  /users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '201':
          description: User created successfully
        '400':
          description: Bad request
      tags:
        - Users
    get:
      summary: Retrieve all Users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: { }
        '404':
          description: Users not found
      tags:
        - Users
  /users/{id}:
    get:
      summary: Retrieve a User by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: { }
        '404':
          description: User not found
      tags:
        - Users
    delete:
      summary: Delete User by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User deleted successfully
        '400':
          description: Bad request
        '404':
          description: User not found
      tags:
        - Users
    patch:
      summary: Update User by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Bad request
        '404':
          description: User not found
      tags:
        - Users
components:
  schemas:
    MultimediaObject:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum: [ IMAGE, VIDEO, TEXT, AUDIO, MULTIDIMENSIONAL ]
        data:
          type: string
        title:
          type: string
        date:
          type: string
        source:
          type: string
        position:
          $ref: '#/components/schemas/MultimediaObjectPosition'
        author:
          type: string
      required:
        - id
        - type
        - data

    MultimediaObjectPosition:
      type: object
      properties:
        lat:
          type: number
          format: double
        lng:
          type: number
          format: double
        bearing:
          type: integer
          format: int32
        yaw:
          type: number
          format: float
      required:
        - lat
        - lng

    MultimediaObjectRequest:
      type: object
      properties:
        type:
          type: string
          enum: [ IMAGE, VIDEO, TEXT, AUDIO, MULTIDIMENSIONAL ]
        title:
          type: string
        date:
          type: string
        source:
          type: string
        position:
          $ref: '#/components/schemas/MultimediaObjectPosition'
        data:
          type: string
        author:
          type: string
      required:
        - id
        - type
        - data

    MultimediaObjectResponse:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum: [ IMAGE, VIDEO, TEXT, AUDIO, MULTIDIMENSIONAL ]
        data:
          type: string
        title:
          type: string
        date:
          type: string
        source:
          type: string
        position:
          $ref: '#/components/schemas/MultimediaObjectPosition'
        author:
          type: string

    Tour:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        source:
          type: string
        multimediaObjects:
          type: array
        author:
          type: string
      required:
        - id
        - title
        - multimediaObjects

    TourRequest:
      type: object
      properties:
        title:
          type: string
        source:
          type: string
        multimediaObjects:
          type: array
        author:
          type: string
      required:
        - id
        - title
        - multimediaObjects

    TourResponse:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        source:
          type: string
        multimediaObjects:
          type: array
        author:
          type: string

    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    LogoutRequest:
      type: object
      properties:
        id:
          type: string
      required:
        - id

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        password:
          type: string
        lastLogin:
          type: string
        activeSessions:
          type: array
        role:
          type: string
      required:
        - id
        - email
        - password

    UserRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        lastLogin:
          type: string
        activeSessions:
          type: array
        role:
          type: string
      required:
        - email
        - password